version: '2.3'

services:

  godigital_qr:
    image: godigital_qr
    container_name: godigital_qr
    working_dir: /data
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PYTHONPATH=/data
      - FLASK_ENV=development
      - FLASK_APP=/data/src/app.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
      - ../:/data
      - ../outputs/:/outputs
    ports:
      - "5000:5000"
    # command: flask run
    command: tail /dev/null -f
